package edu.guilford;

import java.io.IOException;

import javafx.animation.PauseTransition;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import javafx.util.Duration;

/**
 * PRESS class is a subclass of VBox
 * It contains the Button and Label controls for the PRESS pane.
 * The Button control allows the user to generate a random number.
 * The Label control displays the random number generated by the Button.
 * 
 * @Author Gahel Arango and Carlos Ramirez
 * @Version 2.0
 */
public class PRESS extends VBox {

    /**
     * The Button control allows the user to generate a random number
     * The random number is generated when the user clicks the button
     */
    private Button button1;
    /**
     * The Label control displays the random number generated by the Button
     * The random number is updated when the user clicks the button
     */
    private Label messageLabel;

    /**
     * The PRESS constructor initializes the Button and Label controls for the PRESS
     * pane
     * It sets the font and alignment for the controls and adds them to the VBox
     * The constructor also sets an action for the Button to generate a random
     * number
     * and display it in the Label
     */
    public PRESS() {
        super();

        // Create a Button
        button1 = new Button("Click me for a random number!");
        button1.setOnAction(e -> {
            int randomNumber = (int) (Math.random() * 20); // Generate a random number between 0 and 19
            int roundedNumber = (randomNumber / 5) * 5; // Round down to the nearest multiple of 5
            messageLabel.setText("Your random number is: " + roundedNumber);
            getChildren().remove(button1); // Remove the button
            getChildren().add(messageLabel); // Add the message label

         

        });

        // Set font for the button text
        button1.setFont(Font.font("Arial", 16));

        // Create a Label for the message
        messageLabel = new Label();
        messageLabel.setFont(Font.font("Arial", 16));

        setAlignment(Pos.CENTER);

        // Add the button to the VBox
        getChildren().add(button1);
    }

}
